sudo: false
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
branches:
  only:
    - master
    - omnibus/3.2-stable

bundler_args: --jobs 7

before_install: gem install bundler

script: bundle exec rake travis:ci
